spring:
  application.ui.title: "Picture Organizer"

  main:
    allow-circular-references: false
    web-application-type: none

  datasource:
    url: jdbc:h2:file:~/.icroco/db/pictures
#    url: jdbc:h2:mem:pictures
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

logging:
  level:
    root: INFO
    "ch.qos.logback.classic.util": DEBUG
    "org.icroco.javafx": INFO
    "org.icroco.picture.views.task": INFO
    "org.icroco.picture.views.util": INFO
    "org.icroco.picture.views.organize.gallery": INFO

  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(—){faint} %clr([%15.-15t]){faint} %clr(%-50.50logger{49}%4L){cyan} %clr(:){faint} %m%n:-%wEx}"