spring:
  application.ui.title: "Picture Organizer"

  main:
    allow-circular-references: true

  datasource:
    url: jdbc:h2:file:~/.icroco/db/pictures
#    url: jdbc:h2:mem:pictures
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

logging:
  level:
    root: INFO
    org.icroco.javafx: INFO