CREATE TABLE keyword
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64),
    CONSTRAINT PK_KEYWORD PRIMARY KEY (id)
);

CREATE TABLE media
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_path      VARCHAR                                 NOT NULL,
    file_name      VARCHAR(128)                            NOT NULL,
    original_date  TIMESTAMP                               NOT NULL,
    hash           VARCHAR(255),
    hash_creation  date,
    last_access    date,
    collection_id  INT,
    thumbnail_type CHAR,
    orientation    TINYINT,
    keep_or_throw  TINYINT,
    width          INT,
    height         INT,
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    make           VARCHAR(255),
    model          VARCHAR(255),
    CONSTRAINT PK_MEDIA PRIMARY KEY (id)
);

CREATE TABLE media_collection
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    path VARCHAR(1024)                        NOT NULL,
    CONSTRAINT PK_MEDIA_COLLECTION PRIMARY KEY (id)
);

CREATE TABLE media_collection_entry
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    path        VARCHAR                                 NOT NULL,
    sub_path_id INT,
    CONSTRAINT PK_MEDIA_COLLECTION_ENTRY PRIMARY KEY (id)
);

CREATE TABLE mf_keywords
(
    kw_id INT    NOT NULL,
    mf_id BIGINT NOT NULL,
    CONSTRAINT PK_MF_KEYWORDS PRIMARY KEY (kw_id, mf_id)
);

CREATE TABLE thumbnail
(
    mf_id       BIGINT  NOT NULL,
    full_path   VARCHAR NOT NULL,
    image       BLOB,
    origin      VARCHAR(255),
    last_update date,
    CONSTRAINT PK_THUMBNAIL PRIMARY KEY (mf_id)
);

ALTER TABLE keyword
    ADD CONSTRAINT UC_KEYWORD_NAME UNIQUE (name);

ALTER TABLE media_collection
    ADD CONSTRAINT UC_MEDIA_COLLECTION_PATH UNIQUE (path);

ALTER TABLE media
    ADD CONSTRAINT UC_MEDIA_FULL_PATH UNIQUE (full_path);

ALTER TABLE thumbnail
    ADD CONSTRAINT UK_THUMB_PATH UNIQUE (full_path);

ALTER TABLE media_collection_entry
    ADD CONSTRAINT FK_MEDIA_COLLECTION_ENTRY_ON_SUB_PATH FOREIGN KEY (sub_path_id) REFERENCES media_collection (id);

ALTER TABLE media
    ADD CONSTRAINT FK_MEDIA_ON_COLLECTION FOREIGN KEY (collection_id) REFERENCES media_collection (id);

ALTER TABLE mf_keywords
    ADD CONSTRAINT FK_MFKEY_ON_KEYWORD_ENTITY FOREIGN KEY (kw_id) REFERENCES keyword (id);

ALTER TABLE mf_keywords
    ADD CONSTRAINT FK_MFKEY_ON_MEDIA_FILE_ENTITY FOREIGN KEY (mf_id) REFERENCES media (id);