---
name: Compile PRs

on: [ pull_request ]

jobs:
  Build_and_test:

    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          java-package: 'jdk+fx'
          architecture: 'x64'

      - name: Cache Maven packages
        uses: actions/cache@v3
        id: spo-maven
        with:
          path: ~/.m2/repository
          key: spo-maven
          restore-keys: |
            spo-maven

      - name: Compile and test
        run: ./mvnw -B clean verify
